engwed-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: st25556.us-east-2.aws

      # User/password auth
      user: SURABHINIGAM
      password: 90c12152e3f7078c08

      role: SYSADMIN
      database: JAFFLE_SHOP
      warehouse: COMPUTE_WH
      schema: DBT_SURABHINIGAM
      threads: 1
      client_session_keep_alive: False
